{
 "title": "Open Liberty (mpMetrics-2.x)",
 "description": "Visualize MicroProfile Metrics data for your Open Liberty servers.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "base_cpu_processCpuLoad_percent"
   },
   {
    "name": "dur",
    "label": "moving average",
    "query": "[1m],[5m],[10m],[30m],[1h],[1d],[7d]"
   },
   { "name": "heapUsageThreshold", "label": "Heap Usage Threshold (%)", "query": "10,20,30,40,50,60,70,80,90,100" },
   {
    "name": "garbageCollectionThreshold",
    "label": "Garbage Collection Threshold (%)",
    "query": "10,20,30,40,50,60,70,80,90,100"
   },
   {
    "name": "maxHeapUsageProjection",
    "label": "Max Heap Usage Projection (hours)",
    "query": "1"
   },
   { "name": "cpuDur", "query": "[45s]" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Available CPU Processors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "base_cpu_availableProcessors{instance=~`[[instance]]`}",
       "legendFormat": "instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Available CPU Time Percent",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(base_cpu_processCpuTime_seconds{instance=~`[[instance]]`}[[cpuDur]]) / base_cpu_availableProcessors",
       "legendFormat": "instance: {{instance}}"
      }
     ]
    },
    {
     "title": "CPU System Load Average",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "base_cpu_systemLoadAverage{instance=~`[[instance]]`}",
       "legendFormat": "instance: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Instances Above [$heapUsageThreshold%] Heap Usage",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "base_memory_usedHeap_bytes{instance=~`[[instance]]`} / base_memory_maxHeap_bytes{instance=~`[[instance]]`} > [[heapUsageThreshold]]/100"
      }
     ]
    },
    {
     "title": "Increasing Heap Usage Trend Based on Last [[dur]]",
     "type": "table",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "deriv(base_memory_usedHeap_bytes{instance=~`[[instance]]`}[[dur]]) > 0"
      }
     ]
    },
    {
     "title": "Servers That May Reach Max Heap Usage Within [$maxHeapUsageProjection hour(s)] Based on Last [[dur]]",
     "type": "table",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "predict_linear(base_memory_usedHeap_bytes{instance=~`[[instance]]`}[[dur]], [[maxHeapUsageProjection]] * 3600) > base_memory_maxHeap_bytes{instance=~`[[instance]]`}"
      }
     ]
    },
    {
     "title": "Configured Maximum Heap Size",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "base_memory_maxHeap_bytes{instance=~`[[instance]]`}"
      }
     ]
    },
    {
     "title": "Heap Usage Percentage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "base_memory_usedHeap_bytes{instance=~`[[instance]]`} / base_memory_maxHeap_bytes{instance=~`[[instance]]`}",
       "legendFormat": "instance: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Servlets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slowest Servlets Over Last [[dur]] by Average Response Time",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "avg(rate(vendor_servlet_responseTime_total_seconds{instance=~`[[instance]]`}[[dur]]) / rate(vendor_servlet_request_total{instance=~`[[instance]]`}[[dur]])) by (servlet) > 0"
      }
     ]
    },
    {
     "title": "Request Count Over Last [[dur]]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(vendor_servlet_request_total{instance=~`[[instance]]`}[[dur]])",
       "legendFormat": "instance: {{instance}}, servlet: {{servlet}}"
      }
     ]
    },
    {
     "title": "Average Response Time per Request Over Last [[dur]] ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(vendor_servlet_responseTime_total_seconds{instance=~`[[instance]]`}[[dur]])/rate(vendor_servlet_request_total{instance=~`[[instance]]`}[[dur]])",
       "legendFormat": "instance: {{instance}}, servlet: {{servlet}}"
      }
     ]
    },
    {
     "title": "Request Count by Servlet",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vendor_servlet_request_total{instance=~`[[instance]]`}) by (servlet)",
       "legendFormat": "servlet: {{servlet}}"
      }
     ]
    },
    {
     "title": "Average Response Time per Request Over Last [[dur]] by Servlet",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(rate(vendor_servlet_responseTime_total_seconds{instance=~`[[instance]]`}[[dur]]) / rate(vendor_servlet_request_total{instance=~`[[instance]]`}[[dur]])) by (servlet)",
       "legendFormat": "servlet: {{servlet}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connection Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections Used Over Last [[dur]]",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "increase(vendor_connectionpool_usedConnections_total{instance=~`[[instance]]`}[[dur]]) > 0"
      }
     ]
    },
    {
     "title": "Connection Requests Queued Over Last [[dur]]",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "increase(vendor_connectionpool_queuedRequests_total{instance=~`[[instance]]`}[[dur]]) > 0"
      }
     ]
    },
    {
     "title": "Average Time Usage per Connection Over Last [[dur]]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(vendor_connectionpool_inUseTime_total_seconds{instance=~`[[instance]]`}[[dur]]) / rate(vendor_connectionpool_usedConnections_total{instance=~`[[instance]]`}[[dur]]) > 0",
       "legendFormat": "datasource: {{datasource}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Average Wait Time per Queued Connection Request Over Last [[dur]]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(vendor_connectionpool_waitTime_total_seconds{instance=~`[[instance]]`}[[dur]]) / rate(vendor_connectionpool_queuedRequests_total{instance=~`[[instance]]`}[[dur]]) > 0",
       "legendFormat": "datasource: {{datasource}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Managed Connections",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_connectionpool_managedConnections{instance=~`[[instance]]`}",
       "legendFormat": "datasource: {{datasource}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Free Connections",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_connectionpool_freeConnections{instance=~`[[instance]]`}",
       "legendFormat": "datasource: {{datasource}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Connection Handles",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_connectionpool_connectionHandles{instance=~`[[instance]]`}",
       "legendFormat": "datasource: {{datasource}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Create Total",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_connectionpool_create_total{instance=~`[[instance]]`}",
       "legendFormat": "datasource: {{datasource}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Destroy Total",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_connectionpool_destroy_total{instance=~`[[instance]]`}",
       "legendFormat": "datasource: {{datasource}}, instance: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Sessions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_session_activeSessions{instance=~`[[instance]]`}",
       "legendFormat": "appname: {{appname}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Live  Sessions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_session_liveSessions{instance=~`[[instance]]`}",
       "legendFormat": "appname: {{appname}}, instance: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Threadpools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Largest Threadpool Sizes Over Last [[dur]]",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "max_over_time(vendor_threadpool_size{instance=~`[[instance]]`}[[dur]])"
      }
     ]
    },
    {
     "title": "Active Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_threadpool_activeThreads{instance=~`[[instance]]`}",
       "legendFormat": "pool: {{pool}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Threadpool Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_threadpool_size{instance=~`[[instance]]`}",
       "legendFormat": "pool: {{pool}}, instance: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Instances With > [$garbageCollectionThreshold]% of Time Spent Garbage Collecting During Last [[dur]]",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum (rate(base_gc_time_seconds{instance=~`[[instance]]`}[[dur]])) by (instance) > [[garbageCollectionThreshold]] / 100"
      }
     ]
    },
    {
     "title": "Most Time Spent on Garbage Collection Over Last [[dur]]",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "rate(base_gc_time_seconds{instance=~`[[instance]]`}[[dur]]) > 0"
      }
     ]
    },
    {
     "title": "Time per Garbage Collection Cycle [[dur]] moving average",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(base_gc_time_seconds{instance=~`[[instance]]`}[[dur]]) / rate(base_gc_total{instance=~`[[instance]]`}[[dur]])",
       "legendFormat": "instance: {{instance}} name: {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Other JVM Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Uptime",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "base_jvm_uptime_seconds{instance=~`[[instance]]`}"
      }
     ]
    }
   ]
  }
 ]
}