 
global:
  scrape_interval:     15s

  external_labels:
    monitor: 'appsvr'

scrape_configs:
- job_name: 'appsvr'
  scrape_interval: 5s
  metrics_path: '/metrics/'
  static_configs:
  - targets: ['appsvr:9443']
  scheme: https
  tls_config:
    insecure_skip_verify: true